name: Debug
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened
jobs:
  unit-test:
    runs-on:
      - custom
      - linux
      - custom-linux-xl
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      CHECKPOINT_DISABLE: "1"
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: "Add Git safe.directory" # Go 1.18+ started embedding repo info in the build and e.g. building @cdktf/hcl2json fails without this
        run: git config --global --add safe.directory /__w/terraform-cdk/terraform-cdk
      - name: ensure correct user
        run: chown -R root /__w/terraform-cdk
      - name: Get yarn cache directory path
        id: global-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: global-cache # use this to check for `cache-hit` (`steps.global-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.global-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ inputs.terraform_version }}-${{ inputs.package }}
      - name: ensure all plugin directories exist
        run: |
          mkdir -p ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          mkdir -p ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache
      - name: installing dependencies
        run: |
          yarn install --frozen-lockfile --prefer-offline
      - name: compile
        run: |
          tools/align-version.sh
          yarn build
          yarn package
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ inputs.terraform_version }}"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache

      - name: debug
        run: |
          echo "TERRAFORM_BINARY_NAME=$TERRAFORM_BINARY_NAME"
          echo "TF_PLUGIN_CACHE_DIR=$TF_PLUGIN_CACHE_DIR"
          echo "GOCACHE=$GOCACHE"
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ inputs.terraform_version }}"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: DanielMSchmidt,mutahhir
