name: docker

on:
  push:
    branches: main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "website/**"
      - "cdk.tf/**"
      - "tools/update-github-project-board/**"

jobs:
  build-docker-image:
    if: github.repository == 'hashicorp/terraform-cdk'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325
      - name: Cache Docker layers
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('/Dockerfile', '.terraform.versions.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: tf-versions
        run: |
          DEFAULT_TERRAFORM_VERSION=$(cat .terraform.versions.json | jq -r '.default')
          AVAILABLE_TERRAFORM_VERSIONS=$(cat .terraform.versions.json | jq -r '.available | join(" ")')
          echo "default=$DEFAULT_TERRAFORM_VERSION" >> $GITHUB_OUTPUT
          echo "available=$AVAILABLE_TERRAFORM_VERSIONS" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          pull: true
          push: true
          tags: hashicorp/jsii-terraform:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          build-args: |
            DEFAULT_TERRAFORM_VERSION=${{ steps.tf-versions.outputs.default }}
            AVAILABLE_TERRAFORM_VERSIONS=${{ steps.tf-versions.outputs.available }}
