name: Examples Integration
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "website/**"
      - "cdk.tf/**"
      - "tools/update-github-project-board/**"

concurrency:
  group: examples-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint-examples:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: yarn install
      - name: lint examples
        run: yarn lint:examples

  build-example-matrix:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    outputs:
      examples: ${{ steps.set-examples.outputs.examples }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: yarn install
      - name: build and package
        run: |
          yarn build
          yarn package
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - id: set-examples
        run: |
          tfDefault=$(cat .terraform.versions.json | jq -r '.default')
          examples=$(npx lerna list --scope "@examples/*" | jq  -R -s -c --arg tfDefault "${tfDefault}" 'split("\n") | map(select(length > 0)) | { target: values, terraform: [$tfDefault]}')
          echo $examples
          echo "examples=$examples" >> $GITHUB_OUTPUT

  examples:
    needs: build-example-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.build-example-matrix.outputs.examples)}}
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      CHECKPOINT_DISABLE: "1"
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: global-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: global-cache # use this to check for `cache-hit` (`steps.global-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.global-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: installing dependencies
        run: |
          yarn install
      - name: lint
        run: |
          yarn lint:examples
      - name: examples integration tests
        run: test/run-against-dist node tools/build-example.js ${TEST_TARGET}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TEST_TARGET: "${{ matrix.target }}"
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
          MAVEN_OPTS: "-Xmx3G"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache
