name: Provider Integration Tests
on:
  workflow_call:
    inputs:
      skip_setup:
        description: Skip the version and build step and use parent
        default: false
        required: false
        type: boolean
      concurrency_group_prefix:
        default: pr
        required: false
        type: string

concurrency:
  group: ${{ inputs.concurrency_group_prefix }}-provider-integration-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  prepare-provider-tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.build-provider-test-matrix.outputs.tests }}
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      CHECKPOINT_DISABLE: "1"
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Get yarn cache directory path
        id: global-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d
        id: global-cache # use this to check for `cache-hit` (`steps.global-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.global-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: ensure all plugin directories exist
        run: |
          mkdir -p ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          mkdir -p ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache
      - name: installing dependencies and build
        if: ${{ !inputs.skip_setup }}
        run: |
          yarn install --frozen-lockfile --prefer-offline
          tools/align-version.sh "-dev.$GITHUB_RUN_ID"
          yarn build
          yarn package
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ inputs.terraform_version }}"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache
      - name: Upload dist
        if: ${{ !inputs.skip_setup }}
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: dist
          path: dist
      - id: build-provider-test-matrix
        run: |
          ./tools/build-provider-test-matrix.sh

  linux_provider:
    needs: prepare-provider-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare-provider-tests.outputs.tests)}}
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      CHECKPOINT_DISABLE: "1"
      TERRAFORM_VERSION: ${{ matrix.terraform }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Download dist
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: dist
          path: dist
      - name: install test dependencies
        run: cd test && yarn
      - name: integration tests
        run: cd test && npm run test:provider -- ${TEST_TARGET}
        env:
          TEST_TARGET: ${{ matrix.target }}
          NODE_OPTIONS: "--max-old-space-size=7168"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache

  windows_provider:
    needs: prepare-provider-tests
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare-provider-tests.outputs.tests)}}
    env:
      CHECKPOINT_DISABLE: "1"
      TERRAFORM_VERSION: ${{ matrix.terraform }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_wrapper: false
          terraform_version: ${{ matrix.terraform }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.16.x
      - name: Download dist
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: dist
          path: dist
      # tmp fix for https://github.com/npm/cli/issues/4980
      - name: update npm
        run: npm install -g npm@8.12.1
      - name: install test dependencies
        run: cd test && yarn
      - name: integration tests
        run: cd test && ./provider-tests/test-provider.bat ${env:TEST_TARGET}
        env:
          TEST_TARGET: ${{ matrix.target }}
          NODE_OPTIONS: "--max-old-space-size=7168"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.dir }}/terraform-plugins
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.dir }}/go-cache
